//! Auto-generated Markdown bug report.
//!
//! The output is a single self-contained `.md`: every screenshot is embedded as
//! a base64 `data:` URI of the **annotated** image, so pasting the file into a
//! tracker, an issue comment or a chat message shows the mark-up inline with no
//! sidecar files. Screenshots are emitted in capture order (see
//! [`Report::ordered`]), which is what makes a multi-screenshot sequence read as
//! a walkthrough rather than a pile of images.

use crate::base64::png_data_uri;
use crate::model::{
    describe_issues, format_utc, Capture, Report, ReportError, ReportMeta, Severity,
};
use crate::png;

/// Assembles the whole report, or returns every validation problem.
pub fn assemble(report: &Report) -> Result<String, Vec<ReportError>> {
    report.validate()?;
    let ordered = report.ordered();
    let total = ordered.len();
    let mut out = String::with_capacity(4096 + total * 512);

    out.push_str(&format!("# {}\n\n", heading_text(&report.meta.title)));
    out.push_str(&format!(
        "**Severity:** {}  |  **Screenshots:** {}  |  **Annotations:** {}\n\n",
        report.meta.severity.label(),
        total,
        report.annotation_count()
    ));
    if !report.meta.reporter.trim().is_empty() {
        out.push_str(&format!(
            "**Reported by:** {}\n\n",
            one_line(&report.meta.reporter)
        ));
    }
    if !report.meta.summary.trim().is_empty() {
        out.push_str(&format!("{}\n\n", report.meta.summary.trim()));
    }

    let environment = report.meta.environment.rows();
    if !environment.is_empty() {
        out.push_str("## Environment\n\n| Field | Value |\n| --- | --- |\n");
        for (label, value) in environment {
            out.push_str(&format!("| {label} | {} |\n", cell_text(value)));
        }
        out.push('\n');
    }

    let steps = report.meta.clean_steps();
    if !steps.is_empty() {
        out.push_str("## Steps to reproduce\n\n");
        for (index, step) in steps.iter().enumerate() {
            out.push_str(&format!("{}. {}\n", index + 1, one_line(step)));
        }
        out.push('\n');
    }

    out.push_str(&format!("## Screenshots ({total})\n\n"));
    for (index, capture) in ordered.iter().enumerate() {
        out.push_str(&capture_section(capture, index + 1, total));
        if index + 1 < total {
            out.push_str("\n---\n\n");
        }
    }

    out.push_str(&format!(
        "\n_Generated by TPT Bug Report Builder ({} edition) — {} screenshot(s) in capture order._\n",
        crate::model::edition_name(),
        total
    ));
    Ok(out)
}

/// One `### n of m — caption` block: provenance line, inline annotated image,
/// note and the annotation index.
pub fn capture_section(capture: &Capture, position: usize, total: usize) -> String {
    let caption = if capture.title.trim().is_empty() {
        format!("Screenshot {position}")
    } else {
        one_line(&capture.title)
    };
    let mut out = String::with_capacity(1024);
    out.push_str(&format!("### {position} of {total} — {caption}\n\n"));

    let mut provenance = Vec::new();
    if !capture.source.trim().is_empty() {
        provenance.push(format!("Source: {}", one_line(&capture.source)));
    }
    if capture.taken_at_ms > 0.0 {
        provenance.push(format!("Captured: {}", format_utc(capture.taken_at_ms)));
    }
    provenance.push(format!(
        "Image: {} x {} px",
        capture.image.width, capture.image.height
    ));
    if !capture.annotations.is_empty() {
        provenance.push(format!(
            "Mark-up: {} annotation(s)",
            capture.annotations.len()
        ));
    }
    out.push_str(&format!("_{}_\n\n", provenance.join(" | ")));

    let annotated = capture.annotated();
    out.push_str(&format!(
        "![{}]({})\n\n",
        alt_text(&caption),
        png_data_uri(&png::encode(&annotated))
    ));

    if !capture.note.trim().is_empty() {
        out.push_str(&format!("> {}\n\n", one_line(&capture.note)));
    }

    if !capture.annotations.is_empty() {
        out.push_str("Annotations:\n\n");
        for annotation in &capture.annotations {
            out.push_str(&format!("- {}\n", annotation.describe()));
        }
        out.push('\n');
    }
    out
}

/// A one-line summary used by hosts that show a preview before exporting.
pub fn summary(report: &Report) -> String {
    format!(
        "{} — {} ({} screenshot(s), {} annotation(s))",
        heading_text(&report.meta.title),
        report.meta.severity.label(),
        report.captures.len(),
        report.annotation_count()
    )
}

/// The suggested file name for the export.
pub fn file_name(report: &Report) -> String {
    let mut slug = String::new();
    for ch in report.meta.title.trim().chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
        } else if (ch == ' ' || ch == '-' || ch == '_') && !slug.ends_with('-') {
            slug.push('-');
        }
    }
    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "bug-report.md".to_string()
    } else {
        format!("{slug}.md")
    }
}

/// Describes a failed assembly for the UI.
pub fn describe_failure(issues: &[ReportError]) -> String {
    describe_issues(issues)
}

/// Collapses whitespace so a multi-line field cannot break the Markdown layout.
fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Escapes the characters that would change a table cell's meaning.
fn cell_text(text: &str) -> String {
    one_line(text).replace('|', "\\|")
}

/// Strips characters that would break a heading.
fn heading_text(text: &str) -> String {
    let cleaned = one_line(text);
    if cleaned.is_empty() {
        "Bug report".to_string()
    } else {
        cleaned
    }
}

fn alt_text(text: &str) -> String {
    text.replace('[', "(").replace(']', ")")
}

/// Severity as a Markdown-friendly ASCII tag (no emoji, so a downstream tool
/// never has to deal with encoding).
pub fn severity_tag(severity: Severity) -> &'static str {
    match severity {
        Severity::Low => "[low]",
        Severity::Medium => "[medium]",
        Severity::High => "[high]",
        Severity::Critical => "[critical]",
    }
}

/// Metadata-only `(label, value)` rows, used by the PDF writer's first page so
/// the two exports stay in step.
pub fn meta_rows(meta: &ReportMeta) -> Vec<(String, String)> {
    let mut rows = vec![("Severity".to_string(), meta.severity.label().to_string())];
    if !meta.reporter.trim().is_empty() {
        rows.push(("Reported by".to_string(), one_line(&meta.reporter)));
    }
    for (label, value) in meta.environment.rows() {
        rows.push((label.to_string(), one_line(value)));
    }
    rows
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::image::RgbaImage;
    use crate::model::{Capture, Environment, Rect, Severity};

    fn report() -> Report {
        let mut report = Report::new("Export dialog loses its rows");
        report.meta.summary = "The dialog renders only the header.".to_string();
        report.meta.severity = Severity::High;
        report.meta.reporter = "Jane Doe".to_string();
        report.meta.environment = Environment {
            app_name: "Acme Invoicer".to_string(),
            app_version: "1.2.3".to_string(),
            os: "Windows 11 23H2".to_string(),
            browser: "Edge 121".to_string(),
            device: String::new(),
        };
        report.meta.steps = vec![
            "Open the invoices list".to_string(),
            "Select an invoice row".to_string(),
            "   ".to_string(),
            "Click Export".to_string(),
        ];
        let mut capture = Capture::new(1, RgbaImage::filled(48, 32, [255, 255, 255, 255]).expect("image"))
            .with_title("Blank export dialog")
            .with_source("upload: crash.png")
            .with_taken_at_ms(1_700_000_000_000.0);
        capture.note = "Every row after the header is missing.".to_string();
        capture.annotations.push(crate::model::Annotation::Box {
            rect: Rect::new(4, 6, 30, 12),
            color: [211, 47, 47],
            width: 2.0,
        });
        report.push(capture);
        report
    }

    #[test]
    fn assembles_a_readable_single_screenshot_report() {
        let markdown = assemble(&report()).expect("assembles");
        assert!(markdown.starts_with("# Export dialog loses its rows\n"));
        assert!(markdown.contains("**Severity:** High"));
        assert!(markdown.contains("**Reported by:** Jane Doe"));
        assert!(markdown.contains("## Environment"));
        assert!(markdown.contains("| Application | Acme Invoicer |"));
        assert!(markdown.contains("| Operating system | Windows 11 23H2 |"));
        assert!(!markdown.contains("| Device |"), "empty fields are dropped");
        assert!(markdown.contains("## Steps to reproduce\n\n1. Open the invoices list"));
        assert!(markdown.contains("2. Select an invoice row\n3. Click Export"));
        assert!(
            !markdown.contains("4. Click Export"),
            "blank steps are dropped, not numbered"
        );
        assert!(markdown.contains("### 1 of 1 — Blank export dialog"));
        assert!(markdown.contains("_Source: upload: crash.png | Captured: 2023-11-14 22:13:20.000 UTC | Image: 48 x 32 px | Mark-up: 1 annotation(s)_"));
        assert!(markdown.contains("![Blank export dialog](data:image/png;base64,"));
        assert!(markdown.contains("> Every row after the header is missing."));
        assert!(markdown.contains("- Box at (4, 6), 30 x 12, 2 px, red"));
        assert!(markdown.contains(&format!("{} edition", crate::model::edition_name())));
    }

    #[test]
    fn refuses_an_invalid_report() {
        let mut broken = report();
        broken.meta.title = "  ".to_string();
        let issues = assemble(&broken).expect_err("must fail");
        assert!(issues.contains(&ReportError::EmptyTitle));
        assert!(describe_failure(&issues).contains("title"));
    }

    #[test]
    fn collapses_whitespace_so_the_layout_holds() {
        let mut multiline = report();
        multiline.meta.title = "First\nsecond\tline".to_string();
        multiline.meta.reporter = "  Jane\n  Doe  ".to_string();
        let markdown = assemble(&multiline).expect("assembles");
        assert!(markdown.contains("# First second line\n"));
        assert!(markdown.contains("**Reported by:** Jane Doe"));
        assert!(!markdown.contains("\nsecond"));
    }

    #[test]
    fn slugs_the_title_into_a_file_name() {
        let mut named = report();
        assert_eq!(file_name(&named), "export-dialog-loses-its-rows.md");
        named.meta.title = "  ***  ".to_string();
        assert_eq!(file_name(&named), "bug-report.md");
    }

    #[test]
    fn summarises_for_previews() {
        assert_eq!(
            summary(&report()),
            "Export dialog loses its rows — High (1 screenshot(s), 1 annotation(s))"
        );
    }

    #[test]
    fn tags_severities_for_ascii_only_tooling() {
        assert_eq!(severity_tag(Severity::Critical), "[critical]");
        assert_eq!(severity_tag(Severity::Low), "[low]");
    }
}