//! Auto-generated Markdown bug report.
//!
//! [`assemble`] produces a single self-contained `.md`: every screenshot is
//! embedded as a base64 `data:` URI of the **annotated** image, so the file
//! has no sidecar to lose — open it in a browser, Obsidian, Typora, or attach
//! it alone to an email and the mark-up is right there. Screenshots are
//! emitted in capture order (see [`Report::ordered`]), which is what makes a
//! multi-screenshot sequence read as a walkthrough rather than a pile of
//! images.
//!
//! [`assemble_with_sidecars`] trades that self-containment for tracker
//! compatibility: GitHub, GitLab and Jira all strip or refuse to render
//! `data:` URIs in a pasted comment, so a report meant to be pasted into one
//! needs plain `.png` files sitting next to the `.md` with relative links
//! instead.

use crate::base64::png_data_uri;
use crate::model::{
    describe_issues, format_utc, Capture, Report, ReportError, ReportMeta, Severity,
};
use crate::png;

/// Assembles the whole report as a single self-contained `.md`, or returns
/// every validation problem.
pub fn assemble(report: &Report) -> Result<String, Vec<ReportError>> {
    report.validate()?;
    Ok(assemble_body(report, |capture, _| {
        png_data_uri(&png::encode(&capture.annotated()))
    }))
}

/// Assembles the report as a `.md` with relative `![]()` links plus the PNG
/// bytes each one points at — `(file_name, png_bytes)` pairs the caller
/// writes next to the `.md` before handing it (or a zip of the lot) to
/// whoever's filing the bug.
pub fn assemble_with_sidecars(
    report: &Report,
) -> Result<(String, Vec<(String, Vec<u8>)>), Vec<ReportError>> {
    report.validate()?;
    let base = sidecar_stem(report);
    let mut files = Vec::with_capacity(report.captures.len());
    let markdown = assemble_body(report, |capture, position| {
        let name = format!("{base}-{position}.png");
        files.push((name.clone(), png::encode(&capture.annotated())));
        name
    });
    Ok((markdown, files))
}

/// Shared assembly: `image_target(capture, position)` returns whatever goes
/// inside `![alt](...)` for that screenshot — a `data:` URI or a relative
/// file name.
fn assemble_body(report: &Report, mut image_target: impl FnMut(&Capture, usize) -> String) -> String {
    let ordered = report.ordered();
    let total = ordered.len();
    let mut out = String::with_capacity(4096 + total * 512);

    out.push_str(&format!("# {}\n\n", heading_text(&report.meta.title)));
    out.push_str(&format!(
        "**Severity:** {}  |  **Screenshots:** {}  |  **Annotations:** {}\n\n",
        report.meta.severity.label(),
        total,
        report.annotation_count()
    ));
    if !report.meta.reporter.trim().is_empty() {
        out.push_str(&format!(
            "**Reported by:** {}\n\n",
            one_line(&report.meta.reporter)
        ));
    }
    if !report.meta.summary.trim().is_empty() {
        out.push_str(&format!("{}\n\n", report.meta.summary.trim()));
    }

    let environment = report.meta.environment.rows();
    if !environment.is_empty() {
        out.push_str("## Environment\n\n| Field | Value |\n| --- | --- |\n");
        for (label, value) in environment {
            out.push_str(&format!("| {label} | {} |\n", cell_text(value)));
        }
        out.push('\n');
    }

    let steps = report.meta.clean_steps();
    if !steps.is_empty() {
        out.push_str("## Steps to reproduce\n\n");
        for (index, step) in steps.iter().enumerate() {
            out.push_str(&format!("{}. {}\n", index + 1, one_line(step)));
        }
        out.push('\n');
    }

    out.push_str(&format!("## Screenshots ({total})\n\n"));
    for (index, capture) in ordered.iter().enumerate() {
        let position = index + 1;
        let target = image_target(capture, position);
        out.push_str(&capture_section(capture, position, total, target));
        if position < total {
            out.push_str("\n---\n\n");
        }
    }

    out.push_str(&format!(
        "\n_Generated by TPT Bug Report Builder ({} edition) — {} screenshot(s) in capture order._\n",
        crate::model::edition_name(),
        total
    ));
    out
}

/// One `### n of m — caption` block: provenance line, the image (`data:` URI
/// or relative file name, per `image_target`), note and the annotation index.
fn capture_section(capture: &Capture, position: usize, total: usize, image_target: String) -> String {
    let caption = if capture.title.trim().is_empty() {
        format!("Screenshot {position}")
    } else {
        one_line(&capture.title)
    };
    let mut out = String::with_capacity(1024);
    out.push_str(&format!("### {position} of {total} — {caption}\n\n"));

    let mut provenance = Vec::new();
    if !capture.source.trim().is_empty() {
        provenance.push(format!("Source: {}", one_line(&capture.source)));
    }
    if capture.taken_at_ms > 0.0 {
        provenance.push(format!("Captured: {}", format_utc(capture.taken_at_ms)));
    }
    provenance.push(format!(
        "Image: {} x {} px",
        capture.image.width, capture.image.height
    ));
    if !capture.annotations.is_empty() {
        provenance.push(format!(
            "Mark-up: {} annotation(s)",
            capture.annotations.len()
        ));
    }
    out.push_str(&format!("_{}_\n\n", provenance.join(" | ")));

    out.push_str(&format!("![{}]({image_target})\n\n", alt_text(&caption)));

    if !capture.note.trim().is_empty() {
        out.push_str(&format!("> {}\n\n", one_line(&capture.note)));
    }

    if !capture.annotations.is_empty() {
        out.push_str("Annotations:\n\n");
        for annotation in &capture.annotations {
            out.push_str(&format!("- {}\n", annotation.describe()));
        }
        out.push('\n');
    }
    out
}

/// The shared file-name stem sidecar PNGs are numbered under, e.g.
/// `crash-on-export-1.png` — reuses [`file_name`]'s slug so both exports
/// agree on the report's identity.
fn sidecar_stem(report: &Report) -> String {
    file_name(report)
        .strip_suffix(".md")
        .unwrap_or("bug-report")
        .to_string()
}

/// A one-line summary used by hosts that show a preview before exporting.
pub fn summary(report: &Report) -> String {
    format!(
        "{} — {} ({} screenshot(s), {} annotation(s))",
        heading_text(&report.meta.title),
        report.meta.severity.label(),
        report.captures.len(),
        report.annotation_count()
    )
}

/// The suggested file name for the export.
pub fn file_name(report: &Report) -> String {
    let mut slug = String::new();
    for ch in report.meta.title.trim().chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
        } else if (ch == ' ' || ch == '-' || ch == '_') && !slug.ends_with('-') {
            slug.push('-');
        }
    }
    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "bug-report.md".to_string()
    } else {
        format!("{slug}.md")
    }
}

/// Describes a failed assembly for the UI.
pub fn describe_failure(issues: &[ReportError]) -> String {
    describe_issues(issues)
}

/// Collapses whitespace so a multi-line field cannot break the Markdown layout.
fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Escapes the characters that would change a table cell's meaning.
fn cell_text(text: &str) -> String {
    one_line(text).replace('|', "\\|")
}

/// Strips characters that would break a heading.
fn heading_text(text: &str) -> String {
    let cleaned = one_line(text);
    if cleaned.is_empty() {
        "Bug report".to_string()
    } else {
        cleaned
    }
}

fn alt_text(text: &str) -> String {
    text.replace('[', "(").replace(']', ")")
}

/// Severity as a Markdown-friendly ASCII tag (no emoji, so a downstream tool
/// never has to deal with encoding).
pub fn severity_tag(severity: Severity) -> &'static str {
    match severity {
        Severity::Low => "[low]",
        Severity::Medium => "[medium]",
        Severity::High => "[high]",
        Severity::Critical => "[critical]",
    }
}

/// Metadata-only `(label, value)` rows, used by the PDF writer's first page so
/// the two exports stay in step.
pub fn meta_rows(meta: &ReportMeta) -> Vec<(String, String)> {
    let mut rows = vec![("Severity".to_string(), meta.severity.label().to_string())];
    if !meta.reporter.trim().is_empty() {
        rows.push(("Reported by".to_string(), one_line(&meta.reporter)));
    }
    for (label, value) in meta.environment.rows() {
        rows.push((label.to_string(), one_line(value)));
    }
    rows
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::image::RgbaImage;
    use crate::model::{Capture, Environment, Rect, Severity};

    fn report() -> Report {
        let mut report = Report::new("Export dialog loses its rows");
        report.meta.summary = "The dialog renders only the header.".to_string();
        report.meta.severity = Severity::High;
        report.meta.reporter = "Jane Doe".to_string();
        report.meta.environment = Environment {
            app_name: "Acme Invoicer".to_string(),
            app_version: "1.2.3".to_string(),
            os: "Windows 11 23H2".to_string(),
            browser: "Edge 121".to_string(),
            device: String::new(),
        };
        report.meta.steps = vec![
            "Open the invoices list".to_string(),
            "Select an invoice row".to_string(),
            "   ".to_string(),
            "Click Export".to_string(),
        ];
        let mut capture = Capture::new(1, RgbaImage::filled(48, 32, [255, 255, 255, 255]).expect("image"))
            .with_title("Blank export dialog")
            .with_source("upload: crash.png")
            .with_taken_at_ms(1_700_000_000_000.0);
        capture.note = "Every row after the header is missing.".to_string();
        capture.annotations.push(crate::model::Annotation::Box {
            rect: Rect::new(4, 6, 30, 12),
            color: [211, 47, 47],
            width: 2.0,
        });
        report.push(capture);
        report
    }

    #[test]
    fn assembles_a_readable_single_screenshot_report() {
        let markdown = assemble(&report()).expect("assembles");
        assert!(markdown.starts_with("# Export dialog loses its rows\n"));
        assert!(markdown.contains("**Severity:** High"));
        assert!(markdown.contains("**Reported by:** Jane Doe"));
        assert!(markdown.contains("## Environment"));
        assert!(markdown.contains("| Application | Acme Invoicer |"));
        assert!(markdown.contains("| Operating system | Windows 11 23H2 |"));
        assert!(!markdown.contains("| Device |"), "empty fields are dropped");
        assert!(markdown.contains("## Steps to reproduce\n\n1. Open the invoices list"));
        assert!(markdown.contains("2. Select an invoice row\n3. Click Export"));
        assert!(
            !markdown.contains("4. Click Export"),
            "blank steps are dropped, not numbered"
        );
        assert!(markdown.contains("### 1 of 1 — Blank export dialog"));
        assert!(markdown.contains("_Source: upload: crash.png | Captured: 2023-11-14 22:13:20.000 UTC | Image: 48 x 32 px | Mark-up: 1 annotation(s)_"));
        assert!(markdown.contains("![Blank export dialog](data:image/png;base64,"));
        assert!(markdown.contains("> Every row after the header is missing."));
        assert!(markdown.contains("- Box at (4, 6), 30 x 12, 2 px, red"));
        assert!(markdown.contains(&format!("{} edition", crate::model::edition_name())));
    }

    #[test]
    fn refuses_an_invalid_report() {
        let mut broken = report();
        broken.meta.title = "  ".to_string();
        let issues = assemble(&broken).expect_err("must fail");
        assert!(issues.contains(&ReportError::EmptyTitle));
        assert!(describe_failure(&issues).contains("title"));
    }

    #[test]
    fn sidecar_export_links_instead_of_embedding() {
        let (markdown, files) = assemble_with_sidecars(&report()).expect("assembles");
        assert!(
            !markdown.contains("data:image/png;base64,"),
            "sidecar export must not embed the image inline"
        );
        assert!(markdown.contains("![Blank export dialog](export-dialog-loses-its-rows-1.png)"));
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].0, "export-dialog-loses-its-rows-1.png");
        assert!(!files[0].1.is_empty());
        // The file it links to decodes as the same PNG the embedded export
        // would have inlined.
        assert_eq!(files[0].1, png::encode(&report().captures[0].annotated()));
    }

    #[test]
    fn sidecar_export_also_validates_first() {
        let mut broken = report();
        broken.meta.title = "  ".to_string();
        let issues = assemble_with_sidecars(&broken).expect_err("must fail");
        assert!(issues.contains(&ReportError::EmptyTitle));
    }

    // The free edition validates at most one capture, so a second screenshot
    // is only legal under `--features pro`.
    #[cfg(feature = "pro")]
    #[test]
    fn sidecar_export_numbers_every_screenshot() {
        let mut multi = report();
        multi.push(
            Capture::new(2, RgbaImage::filled(8, 8, [0, 0, 0, 255]).expect("image"))
                .with_taken_at_ms(1_700_000_001_000.0),
        );
        let (markdown, files) = assemble_with_sidecars(&multi).expect("assembles");
        assert_eq!(files.len(), 2);
        assert_eq!(files[0].0, "export-dialog-loses-its-rows-1.png");
        assert_eq!(files[1].0, "export-dialog-loses-its-rows-2.png");
        assert!(markdown.contains("](export-dialog-loses-its-rows-1.png)"));
        assert!(markdown.contains("](export-dialog-loses-its-rows-2.png)"));
    }
    fn collapses_whitespace_so_the_layout_holds() {
        let mut multiline = report();
        multiline.meta.title = "First\nsecond\tline".to_string();
        multiline.meta.reporter = "  Jane\n  Doe  ".to_string();
        let markdown = assemble(&multiline).expect("assembles");
        assert!(markdown.contains("# First second line\n"));
        assert!(markdown.contains("**Reported by:** Jane Doe"));
        assert!(!markdown.contains("\nsecond"));
    }

    #[test]
    fn slugs_the_title_into_a_file_name() {
        let mut named = report();
        assert_eq!(file_name(&named), "export-dialog-loses-its-rows.md");
        named.meta.title = "  ***  ".to_string();
        assert_eq!(file_name(&named), "bug-report.md");
    }

    #[test]
    fn summarises_for_previews() {
        assert_eq!(
            summary(&report()),
            "Export dialog loses its rows — High (1 screenshot(s), 1 annotation(s))"
        );
    }

    #[test]
    fn tags_severities_for_ascii_only_tooling() {
        assert_eq!(severity_tag(Severity::Critical), "[critical]");
        assert_eq!(severity_tag(Severity::Low), "[low]");
    }
}